# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: ubuntu_20_04_mem_pool_on
  displayName: 'Build - Ubuntu 18.04 - With Memory Pool'
  continueOnError: false
  pool:
    vmImage: 'Ubuntu 20.04'
  workspace:
    clean: all
  steps:
    - script: |
        mkdir build
    - script: |
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
      displayName: 'CMake'
      workingDirectory: build
    - task: CopyFiles@2
      displayName: "Copy headers"
      inputs:
        SourceFolder: "src/oatpp/"
        Contents: "**/?(*.h|*.hpp)"
        TargetFolder: $(Build.ArtifactStagingDirectory)/includes/
    - task: CopyFiles@2
      displayName: "Copy Library"
      inputs:
        SourceFolder: "./"
        Contents: "**/*.a"
        TargetFolder: $(Build.ArtifactStagingDirectory)/lib/linux/
    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifacts"
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: Artifacts
